### ISSUE TITLE
wisp dont compile on Debian/x86-64 with GCC 

### ISSUE THREAD

**Issue by bstarynk** [adam-mcdaniel/wisp#11]
Hello Adam,
Compilation of your `wisp` (commit `9d83b03b0225`  on Linux/[Debian](https://debian.org/)/x86-64 with [GCC](https://gcc.gnu.org/)  version 12.2 using
```
g++ -Wall -Wextra -O -g wisp.cpp -o wisp
```

is failing with 
```
wisp.cpp: In member function ‘std::string Value::display() const’:
wisp.cpp:95:24: error: invalid ‘static_cast’ from type ‘std::__cxx11::basic_ostringstream<char>’ to type ‘std::ostringstream&’ {aka ‘std::__cxx11::basic_ostringstream<char>&’}
   95 | #define to_string( x ) static_cast<std::ostringstream&>((std::ostringstream() << std::dec << x )).str()
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wisp.cpp:695:20: note: in expansion of macro ‘to_string’
  695 |             return to_string(stack_data.i);
      |                    ^~~~~~~~~
```

I am considering using your most of `wisp` code in the [clever-framac](https://github.com/bstarynk/misc-basile/blob/master/clever-framac.cc) driver (GPLv3+ licensed) for [Frama-C](https://frama-c.com/) static analyzer.

My pet open source project is the [RefPerSys](http://refpersys.org/) free software inference engine 

Regards.
[Basile Starynkevitch](http://starynkevitch.net/Basile/) working at [CEA LIST](https://list.cea.fr/)
email at office: `basile.starynkevitch@cea.fr` at home `basile@starynkevitch.net`

**Comment by adam-mcdaniel** [comment]
Hello, pull request #12 might fix your issue, as it removes the `static_cast` entirely. Let me know if this works.

**Comment by bstarynk** [comment]
Thanks. I can compile it now and it works (commit a6f7782a1c on Debian)
