### ISSUE TITLE
EOF on stdin gives infinite loop

### ISSUE THREAD

**Issue by bstarynk** [adam-mcdaniel/wisp#13]
In commit a6f7782a1c00b8 of `wisp` (compiled on a [Ubuntu](https://ubuntu.com/) 23 desktop with x86-64 AMD Ryzen 2970WX, with GCC version 13.2, invoked as
```
 g++ -O -g wisp.cpp -o wisp
```
an end-of-file (entered by pressing together the keys _Ctrl-D_) gives an **infinite loop**.

Regards from near Paris in France from [Basile Starynkevitch](mailto:basile@starynkevitch.net) who is seeking partners interested by the [RefPerSys](https://github.com/RefPerSys/RefPerSys/) open source inference engine project (on github). Contact me by email to `basile@starynkevitch.net`

**Comment by adam-mcdaniel** [comment]
Fixed by #14
